services:
  # Frontend development service with hot reload
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - astroloh-network
    command: npm run dev -- --host 0.0.0.0

  # Backend service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - DATABASE_URL=postgresql+asyncpg://astroloh_user:astroloh_password@db:5432/astroloh_db
    depends_on:
      - db
    volumes:
      - ./app:/app/app
      - ./migrations:/app/migrations
      - ./alembic.ini:/app/alembic.ini
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - astroloh-network

  # Database service
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: astroloh_user
      POSTGRES_PASSWORD: astroloh_password
      POSTGRES_DB: astroloh_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - astroloh-network

volumes:
  postgres_data:

networks:
  astroloh-network:
    driver: bridge